### ISSUE TITLE
Innlogging virker ikke

### ISSUE THREAD

**Issue by ingeremma** [Samfundet/fg#33]
Prøvde nettopp å logge inn med brukernavn og passord skrevet i møtereferatet. (Fra pc hjemme) Det skjer ingenting når jeg trykker på "logg inn" eller trykker enter. Altså ingenting, som i at innloggingsbildet forblir åpent, det virker heller ikke som om jeg blir logget inn uten at vinduet forsvinner. "lukk"-knappen fungerer heller ikke. Det går ikke an å gjøre noe egentlig, kan trykke rundt overalt uten at noe skjer.

**Comment by jhnoor** [comment]
@ingeremma dette er fgbeta.samfundet.no ikkesant? Kan du prøve igjen og skrive hvilken nettleser og OS du bruker?

**Comment by ingeremma** [comment]
fgbeta ja.

Prøvde igjen. Nå forsvant diologboksen, men virker ikke som om jeg blir logget inn. Chrome og windows 10.

**Comment by jhnoor** [comment]
@ingeremma innlogging gir litt bedre tilbakemelding nå om den feiler - prøv igjen men med små bokstaver til brukernavnet så skal det virke litt bedre nå 👍

**Comment by ghost** [comment]
Smooth, funka nå :-) (fra Android 8.1)

6. jan. 2018 00:35 skrev "Jama Noor" <notifications@github.com>:
