### ISSUE TITLE
@frontend lange tags forsvinner ut av "tags feltet" under opplasting av bilder

### ISSUE THREAD

**Issue by sjsivert** [Samfundet/fg#52]
![image](https://user-images.githubusercontent.com/5860069/36643418-3f8b900a-1a4b-11e8-8b22-fda094a21ee1.png)

**Comment by sjsivert** [comment]
Liten forbedring. Kan gjøres bedre
![image](https://user-images.githubusercontent.com/5860069/36644311-8a371130-1a58-11e8-8061-d2f15b48c81d.png)

TODO: Fikk ikke til å gjøre reglen for KUN text-input-box--tags CSS klassen. Endringenen gjelder nå for HELE text-input-box klassen.

**Comment by Mikkel94** [comment]
<img width="671" alt="screen shot 2018-02-26 at 5 19 33 pm" src="https://user-images.githubusercontent.com/22194628/36681586-5bd151a4-1b19-11e8-9fd2-371997101ca9.png">

La til wrapping til chips, Hvis dere syns dette ser good ut si fra så closer vi issue
