### ISSUE TITLE
@frontend: ERROR TypeError: Cannot read property 'indexOf' of undefined

### ISSUE THREAD

**Issue by Mikkel94** [Samfundet/fg#53]
Dette skjer når det ikke er noen bilder i handlekurven i localstorage. Feil finnes i photo-masonry component i ngOnInit metode

**Comment by sjsivert** [comment]
Copy/paste facebook chat:

Skjønte ikke helt hva du mente 
> med This doesn't work in search because this.photo does not contain pid

For meg ser det ut som om inCartPhotos er undefined og du prøver å løse det ved å iterere over inCartPhotos først for hvert bildet i this.photos i tilfelle inCartPhotos ikke eksisterer?

Får nå en syntax error `[ts] expression expected` av vscode
