### ISSUE TITLE
@frontend: Bruk Lodash kanskje?

### ISSUE THREAD

**Issue by Mikkel94** [Samfundet/fg#59]
Det er minst et sted det er greit å bruke, så ha det i bakhodet, husker ikke hvor. Denne issue kan egt ignoreres. Underscore bibiliteket er goså mulig å bruke. Same shit

**Comment by Mikkel94** [comment]
Lodash added, it is used so few places (only pagination component for noe) so it is probably a good idea to remove ot

**Comment by Mikkel94** [comment]
http://shzhangji.com/blog/2017/03/13/why-use-lodash-when-es6-is-available/

Les denne. Skal vi bytte ut ting med lodash eller beholde slik som det er? Syns lodash er veldig clean selv.

**Comment by jhnoor** [comment]
Lodash er bra, ikke så tung heller og veldig kraftig funksjonell progging
