### ISSUE TITLE
@frontend: Fix pagination for search

### ISSUE THREAD

**Issue by Mikkel94** [Samfundet/fg#60]
https://github.com/michaelbromley/ngx-pagination

tenker jeg kan funke? har lagt til i package.json og app.module

Paginator for photos in backend updated, use this.

Front page må også fikses for den ble fucked av den nye paginator classen

Eller faktisk like greit å lage en egen component til dette: utils/pagination, så kan vi holde samme stil over hele nettsiden lettere

**Comment by Mikkel94** [comment]
Pagination component added.

What is left: design

**Comment by sjsivert** [comment]
update: [bilde](https://i.imgur.com/5uuKbrw.jpg)
